# dotnet nuget push AppLogger.1.0.0.nupkg --api-key qz2jga8pl3dvn2akksyquwcs9ygggg4exypy3bhxy6w6x6 --source https://api.nuget.org/v3/index.json

language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 5.0

script:
  - dotnet restore
  - dotnet build
  - dotnet test AsyncLock.Unit.Test/AsyncLock.Unit.Test.csproj

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1